PURGE RECYCLEBIN;

SET SERVEROUTPUT ON;

-- Creating WAREHOUSE_OWNER, WAREHOUSE_CUSTOMER, WAREHOUSE_EMPLOYEE ROLES

-- Drop the WAREHOUSE_OWNER role if already exists
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE WAREHOUSE_OWNER ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1919 THEN
           dbms_output.put_line('ROLE WAREHOUSE_OWNER does not exist. Proceeding to create the role');
        END IF;
END;
/

--Creatiing the role and granting permissions to WAREHOUSE_OWNER
CREATE ROLE WAREHOUSE_OWNER;

GRANT CONNECT TO WAREHOUSE_OWNER;
GRANT CREATE SESSION TO WAREHOUSE_OWNER;

GRANT SELECT ON Owners_Revenue_By_Warehouse TO WAREHOUSE_OWNER;
GRANT SELECT ON warehouse_availability_status_view TO WAREHOUSE_OWNER;

GRANT UPDATE (Owner_Name, Street_Address, Email, Phone) ON WAREHOUSE_APP_ADMIN_USER.WAREHOUSE_OWNER TO WAREHOUSE_OWNER;

-- GRANTING EXECUTE PERMISSIONS TO WAREHOUSE_OWNER

GRANT EXECUTE ON InsertWarehouseWithLocationAndType TO WAREHOUSE_OWNER;

GRANT EXECUTE ON UPDATE_OWNER_INFO TO WAREHOUSE_OWNER;

-- Drop the user if already exists
BEGIN
    EXECUTE IMMEDIATE 'DROP USER WAREHOUSE_OWNER_USER CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            dbms_output.put_line('User WAREHOUSE_OWNER_USER does not exist. Proceeding to create the user');
        END IF;
END;
/
-- CREATE WAREHOUSE_OWNER_USER AND ASSIGN WAREHOUSE_OWNER ROLE

CREATE USER WAREHOUSE_OWNER_USER IDENTIFIED BY BostonSpring2024#;
GRANT WAREHOUSE_OWNER TO WAREHOUSE_OWNER_USER;
ALTER USER WAREHOUSE_OWNER_USER DEFAULT ROLE WAREHOUSE_OWNER;
ALTER USER WAREHOUSE_OWNER_USER DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER WAREHOUSE_OWNER_USER TEMPORARY TABLESPACE TEMP;



-- Drop the role if already exists
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE WAREHOUSE_CUSTOMER ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1919 THEN
            dbms_output.put_line('ROLE WAREHOUSE_CUSTOMER does not exist. Proceeding to create the role');
        END IF;
END;
/


-- Creating the WAREHOUSE_CUSTOMER role and granting permissions to WAREHOUSE_CUSTOMER

CREATE ROLE WAREHOUSE_CUSTOMER;
GRANT CONNECT TO WAREHOUSE_CUSTOMER;
GRANT CREATE SESSION TO WAREHOUSE_CUSTOMER;
GRANT UPDATE (First_Name, Last_Name, Street_Address, Email, Phone) ON WAREHOUSE_APP_ADMIN_USER.CUSTOMER TO WAREHOUSE_CUSTOMER;
GRANT INSERT ON WAREHOUSE_APP_ADMIN_USER.CUSTOMER TO WAREHOUSE_CUSTOMER;
GRANT SELECT ON customer_lease_details_view TO WAREHOUSE_CUSTOMER;
GRANT SELECT ON service_request_status_warehouse_view TO WAREHOUSE_CUSTOMER;
GRANT SELECT ON payment_summary_view TO WAREHOUSE_CUSTOMER;
GRANT EXECUTE ON customer_makes_transaction TO WAREHOUSE_CUSTOMER;

GRANT EXECUTE ON INSERT_CUSTOMER_RECORD TO WAREHOUSE_CUSTOMER;

GRANT EXECUTE ON UPDATE_CUSTOMER_INFO TO WAREHOUSE_CUSTOMER;

GRANT EXECUTE ON DELETE_CUSTOMER TO WAREHOUSE_CUSTOMER;

GRANT EXECUTE ON InsertLease TO WAREHOUSE_CUSTOMER;

GRANT EXECUTE ON process_payment TO WAREHOUSE_CUSTOMER;

GRANT EXECUTE ON customer_makes_transaction TO WAREHOUSE_CUSTOMER;

GRANT EXECUTE ON CancelLease TO WAREHOUSE_CUSTOMER;

GRANT EXECUTE ON ExtendLease TO WAREHOUSE_CUSTOMER;

GRANT EXECUTE ON InsertServiceRequest TO WAREHOUSE_CUSTOMER;


-- CREATE WAREHOUSE_CUSTOMER_USER AND ASSIGN WAREHOUSE_CUSTOMER ROLE
-- Drop the user if already exists
BEGIN
    EXECUTE IMMEDIATE 'DROP USER WAREHOUSE_CUSTOMER_USER CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            dbms_output.put_line('User WAREHOUSE_CUSTOMER_USER does not exist. Proceeding to create the user');
        END IF;
END;
/

CREATE USER WAREHOUSE_CUSTOMER_USER IDENTIFIED BY BostonSpring2024#;
GRANT WAREHOUSE_CUSTOMER TO WAREHOUSE_CUSTOMER_USER;
ALTER USER WAREHOUSE_CUSTOMER_USER DEFAULT ROLE WAREHOUSE_CUSTOMER;
ALTER USER WAREHOUSE_CUSTOMER_USER DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER WAREHOUSE_CUSTOMER_USER TEMPORARY TABLESPACE TEMP;


-- CREATE AND GRANT PERMISSIONS TO WAREHOUSE_EMPLOYEE ROLE
-- Drop the role if already exists
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE WAREHOUSE_EMPLOYEE ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1919 THEN
             dbms_output.put_line('ROLE WAREHOUSE_EMPLOYEE does not exist. Proceeding to create the role');
        END IF;
END;
/ 
CREATE ROLE WAREHOUSE_EMPLOYEE;
GRANT CONNECT TO WAREHOUSE_EMPLOYEE;
GRANT CREATE SESSION TO WAREHOUSE_EMPLOYEE;

-- CREATE WAREHOUSE_EMPLOYEE_USER AND ASSIGN WAREHOUSE_EMPLOYEE ROLE
-- Drop the user if already exists
BEGIN
    EXECUTE IMMEDIATE 'DROP USER WAREHOUSE_EMPLOYEE_USER CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            dbms_output.put_line('User WAREHOUSE_EMPLOYEE_USER does not exist. Proceeding to create the user');
        END IF;
END;
/
CREATE USER WAREHOUSE_EMPLOYEE_USER IDENTIFIED BY BostonSpring2024#;
GRANT WAREHOUSE_EMPLOYEE TO WAREHOUSE_EMPLOYEE_USER;
ALTER USER WAREHOUSE_EMPLOYEE_USER DEFAULT ROLE WAREHOUSE_EMPLOYEE;
ALTER USER WAREHOUSE_EMPLOYEE_USER DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER WAREHOUSE_EMPLOYEE_USER TEMPORARY TABLESPACE TEMP;
GRANT UPDATE (EMPLOYEE_NAME, Street_Address, EMAIL, PHONE) ON WAREHOUSE_APP_ADMIN_USER.WAREHOUSE_EMPLOYEE TO WAREHOUSE_EMPLOYEE;
